apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
spec:
  selector:
    matchLabels:
      app: recipe-service
  
  template:
    metadata:
      labels:
        app: recipe-service
    
    spec:
      serviceAccountName: api-reader
      containers:
      - name: recipe-service
        image: phjppo0918/haru-han-jan-recipe-service
        imagePullPolicy: Always
        volumeMounts:
          - name: recipe-secret
            mountPath: /secrets
        ports:
        - containerPort: 8080

      volumes:
      - name: recipe-secret
        secret:
          secretName: recipe-secret

    
