apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
spec:
  selector:
    matchLabels:
      app: recipe-service

  template:
    metadata:
      labels:
        app: recipe-service

    spec:
      serviceAccountName: api-reader
      containers:
        - name: recipe-service
          image: phjppo0918/haru-han-jan-recipe-service
          imagePullPolicy: Always

          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: alcohol-secret
                  key: database.host

            - name: DATABASE_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: alcohol-secret
                  key: database.schema

            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: alcohol-secret
                  key: database.username

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alcohol-secret
                  key: database.password

          ports:
            - containerPort: 8080
