resources:
  - "deployment.yml"
  - "service.yml"
  - "role.yml"

configMapGenerator:
- name: recipe-service-configmap-dev
  options:
    disableNameSuffixHash: true
  files:
    - bootstrap-dev.yml

secretGenerator:
  - name: recipe-secret
    envs:
      - secret.env

      