apiVersion: v1
kind: Secret
metadata:
  name: recipe-secret
type: Opaque
data:
  database.username: "cm9vdA=="
  database.password: "MTIzNA=="
  database.host: "cmVjaXBlLW15c3Fs"
  database.schema: "aGFydWRi"
