apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  selector:
    app: authentication
  ports:
  - port: 8080
    targetPort: 8080
  #type: LoadBalancer
