apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  selector:
    matchLabels:
      app: authentication
  
  template:
    metadata:
      labels:
        app: authentication
    
    spec:
      serviceAccountName: api-reader
      containers:
      - name: authentication
        image: phjppo0918/haru-han-jan-authentication
        imagePullPolicy: Always

        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: authentication-secret
                key: DATABASE_HOST

          - name: DATABASE_SCHEMA
            valueFrom:
              secretKeyRef:
                name: authentication-secret
                key: DATABASE_SCHEMA
                
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: authentication-secret
                key: DATABASE_USERNAME

          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: authentication-secret
                key: DATABASE_PASSWORD

              

        
        ports:
        - containerPort: 8080



    
