apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  selector:
    matchLabels:
      app: authentication
  
  template:
    metadata:
      labels:
        app: authentication
    
    spec:
      serviceAccountName: api-reader
      containers:
      - name: authentication
        image: phjppo0918/haru-han-jan-authentication
        imagePullPolicy: Always
        volumeMounts:
          - name: authentication-secret
            mountPath: /secrets
        ports:
        - containerPort: 8080
      volumes:
      - name: authentication-secret
        secret:
          secretName: authentication-secret


    
