resources:
  - deployment.yml
  - service.yml
  - role.yml

configMapGenerator:
  - name: authentication-configmap-dev
    options:
      disableNameSuffixHash: true
    files:
      - application-dev.yml

secretGenerator:
  - name: authentication-secret
    envs:
      - secret.env