resources:
  - deployment.yml
  - service.yml
  - role.yml

configMapGenerator:
  - name: authentication-configmap-dev
    namespace: authentication
    options:
      disableNameSuffixHash: true
    files:
      - bootstrap-dev.yml

secretGenerator:
  - name: authentication-secret
    envs:
      - secret.env