resources:
  - deployment.yml
  - service.yml
  - role.yml
  - secret.yml

configMapGenerator:
  - name: authentication-configmap-dev
    options:
      disableNameSuffixHash: true
    files:
      - application-dev.yml