apiVersion: v1
kind: Secret
metadata:
  name: authentication-secret
type: Opaque
data:
  database.username: "cm9vdA=="
  database.password: "MTIzNA=="
  database.host: "YXV0aC1teXNxbA=="
  database.schema: "aGFydWRi"

  oauth2.github.clientId: ""
  oauth2.github.secret: ""
  oauth2.google.clientId: ""
  oauth2.google.secret: ""
  oauth2.kakao.clientId: ""
  oauth2.naver.clientId: ""
  oauth2.naver.secret: ""

  jwt.secret: "c2Rmc2hydXdldGlqaWxmZHpqZ2xpajIzbzQ4NDVvamZkZ29qc296ZGpmb2lqb2lqbzQ2MDk4YXVkd3Rpc2RmNDU1NzQ1cnlzcnRoaG5hZXJmY2pvaTJqMzRvY2lmam9pdGgK"