apiVersion: apps/v1
kind: Deployment
metadata:
  name: alcohol-service
spec:
  selector:
    matchLabels:
      app: alcohol-service
  template:
    metadata:
      labels:
        app: alcohol-service
    spec:
      serviceAccountName: api-reader
      containers:
      - name: alcohol-service
        image: phjppo0918/haru-han-jan-alcohol-service
        imagePullPolicy: Always
        volumeMounts:
          - name: alcohol-secret
            mountPath: /secrets

        ports:
          - containerPort: 8080
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "2"

      volumes:
      - name: alcohol-secret
        secret:
          secretName: alcohol-secret
