apiVersion: apps/v1
kind: Deployment
metadata:
  name: alcohol-service
spec:
  selector:
    matchLabels:
      app: alcohol-service
  template:
    metadata:
      labels:
        app: alcohol-service
    spec:
      serviceAccountName: api-reader
      containers:
      - name: alcohol-service
        image: phjppo0918/haru-han-jan-alcohol-service
        imagePullPolicy: Always

        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: alcohol-secret
                key: database.host

          - name: DATABASE_SCHEMA
            valueFrom:
              secretKeyRef:
                name: alcohol-secret
                key: database.schema
                
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: alcohol-secret
                key: database.username

          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: alcohol-secret
                key: database.password

        ports:
          - containerPort: 8080
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "2"

