resources:
  - deployment.yml
  - service.yml
  - role.yml
  - secret.yml

configMapGenerator:
  - name: alcohol-service-configmap
    options:
      disableNameSuffixHash: true
    files:
      - bootstrap-dev.yml

