resources:
  - deployment.yml
  - service.yml
  - role.yml

configMapGenerator:
  - name: alcohol-service-configmap
    options:
      disableNameSuffixHash: true
    files:
      - bootstrap-dev.yml

secretGenerator:
  - name: alcohol-secret
    envs:
      - secret.env
