apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: "wurstmeister/kafka"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: 172.18.0.101
          - name: KAFKA_PORT
            value: "9092"
        depends_on: 
        ports:
        - containerPort: 9092
