 apiVersion: v1 
 kind: Service 
 metadata:  
   labels:  
     app: kafka
   name: kafka
 spec:  
   ports:  
     - port: 9092 
       name: producer 
       targetPort: 9092
       protocol: TCP
     - port: 2181 
       name: consumer
       targetPort: 2181 
   selector:  
     app: kafka
   type: LoadBalancer