apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mysql
  labels:
    app: order-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-mysql
    spec:
      containers:
      - name: order-mysql
        image: mysql:latest
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: order-mysql-volume
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: harudb
        ports:
        - containerPort: 3306

      volumes:
      - name: order-mysql-volume
        hostPath:
          path: /volume/data/order   
