apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-mysql
  labels:
    app: recipe-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recipe-mysql
    spec:
      containers:
      - name: recipe-mysql
        image: mysql:latest
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: recipe-mysql-volume
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: database-secret
                key: database.password
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: database-secret
                key: database.schema
        ports:
        - containerPort: 3306

      volumes:
      - name: recipe-mysql-volume
        hostPath:
          path: /volume/data/recipe  
