apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  
  template:
    metadata:
      labels:
        app: order-service
    
    spec:
      serviceAccountName: api-reader
      containers:
      - name: recipe-service
        image: phjppo0918/haru-han-jan-order-service
        imagePullPolicy: Always
        envFrom:
          - recipeSecret
        ports:
        - containerPort: 8080

    
