apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  
  template:
    metadata:
      labels:
        app: order-service
    
    spec:
      serviceAccountName: api-reader
      containers:
      - name: order-service
        image: phjppo0918/haru-han-jan-order-service
        imagePullPolicy: Always
        volumeMounts:
          - name: order-secret
            mountPath: /secrets
        ports:
        - containerPort: 8080

      volumes:
      - name: order-secret
        secret:
          secretName: order-secret

    
