resources:
  - "deployment.yml"
  - "service.yml"
  - "role.yml"
  - "secret.yml"

configMapGenerator:
- name: order-service-configmap-dev
  options:
    disableNameSuffixHash: true
  files:
    - bootstrap-dev.yml

      